apiVersion: sources.knative.dev/v1alpha2
kind: ContainerSource
metadata:
  name: test-heartbeats
spec:
  template:
    spec:
      containers:
        - image: docker.io/petlab/sampleworkload
          name: heartbeats
          env:
            - name: K_SINK
              value: http://broker-ingress.knative-eventing.svc.cluster.local/default/default
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
